import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../components/Sidebar/Sidebar";

const sidebarItems = [
  { label: "Dashboard", href: "/", icon: "🏠" },
  { label: "Users", href: "/users", icon: "👥" },
  { label: "Settings", href: "/setup", icon: "⚙️" },
  { label: "About", href: "/lol", icon: "🤔" },
];


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar items={sidebarItems} />
          <main className="flex-1 p-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
